### ISSUE TITLE
Demo fails to run on Intel 2nd Generation Integrated Graphics

### ISSUE THREAD

**Issue by yatsam** [floooh/cimgui-sokol-starterkit#21]
Hi,
Thank you very much for your work.
I am a beginner in C programming and want to learn the sokol library for a project involving graphics. Would appreciate your help in solving this issue.
On a Debian 12 PC, after building the demo application of the cimgui-sokol-starterkit and running it, I get the following error message:

[sapp][warning][id:49] /home/samyh/programs/c/cimgui-sokol-starterkit/sokol/sokol_app.h:10119:0: 
	LINUX_X11_QUERY_SYSTEM_DPI_FAILED: failed to query system dpi value, assuming default 96.0

[sapp][panic][id:35] /home/samyh/programs/c/cimgui-sokol-starterkit/sokol/sokol_app.h:10351:0: 
	LINUX_GLX_CREATE_CONTEXT_FAILED: Failed to create GL context via glXCreateContextAttribsARB

ABORTING because of [panic]
Aborted
___________________________________________

Ignoring the warning, I then updated the sokol_main function in demo.c file as per the following (last 3 lines) to count for the fact that the OpenGL max core profile version of my graphics card is 3.3 (as per solution found at https://bbs.archlinux.org/viewtopic.php?id=301469. 

`sapp_desc sokol_main(int argc, char* argv[]) {
    (void)argc;
    (void)argv;
    return (sapp_desc){
        .init_cb = init,
        .frame_cb = frame,
        .cleanup_cb = cleanup,
        .event_cb = event,
        .window_title = "Hello Sokol + Dear ImGui",
        .width = 800,
        .height = 600,
        .icon.sokol_default = true,
        .logger.func = slog_func,
        .gl_major_version = 3,
        .gl_minor_version = 3,
        .init_cb = init,
    };
}`

The output of the build and run is the following:

[sapp][warning][id:49] /home/samyh/programs/c/cimgui-sokol-starterkit/sokol/sokol_app.h:10119:0: 
	LINUX_X11_QUERY_SYSTEM_DPI_FAILED: failed to query system dpi value, assuming default 96.0

[sg][error][id:5] /home/samyh/programs/c/cimgui-sokol-starterkit/sokol/sokol_gfx.h:8683:0: 
	GL_SHADER_COMPILATION_FAILED: shader compilation failed (gl)

[sg][info][id:5] /home/samyh/programs/c/cimgui-sokol-starterkit/sokol/sokol_gfx.h:8684:0: 
	0:1(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES

[sg][error][id:5] /home/samyh/programs/c/cimgui-sokol-starterkit/sokol/sokol_gfx.h:8683:0: 
	GL_SHADER_COMPILATION_FAILED: shader compilation failed (gl)

[sg][info][id:5] /home/samyh/programs/c/cimgui-sokol-starterkit/sokol/sokol_gfx.h:8684:0: 
	0:1(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES

[sg][error][id:177] /home/samyh/programs/c/cimgui-sokol-starterkit/sokol/sokol_gfx.h:16956:0: 
	VALIDATE_PIPELINEDESC_SHADER: sg_pipeline_desc.shader missing or invalid

[sg][panic][id:296] /home/samyh/programs/c/cimgui-sokol-starterkit/sokol/sokol_gfx.h:16497:0: 
	VALIDATION_FAILED: validation layer checks failed

ABORTING because of [panic]
Aborted
___________________________________________

I could not find any solution to the [panic] error message. All my drivers are up to date and I can use a program like blender without any problem on this PC, even though it is now a bit old (Thinkpad X220). The glxgears test program also runs normally.
The problem described above also occurs when running the sokol-samples.

Here below is the output of glxinfo -p:

name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 3000 (SNB GT2) (0x126)
    Version: 22.3.6
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.3
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 3000 (SNB GT2)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 22.3.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.3 (Compatibility Profile) Mesa 22.3.6
OpenGL shading language version string: 3.30
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 22.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
___________________________________________

Many thanks in advance!

**Comment by floooh** [comment]
Yeah, sorry about that, but Intel HD doesn't support at least GL 4.1 (even though you can force a lower GL version, and sokol_gfx.h might even still work with GL 3.3 - but that won't be guaranteed for the future).

As you noticed, the problem are the embedded GLSL shader blobs, which are hardwired to GLSL 4.1.

However, sokol_app.h also supports GLES3 on Linux with the right compilation options (this was mainly added for debugging support though), so that might be worth a try (since your glxinfo shows support for GLES 3.0).

E.g. replace this line:

https://github.com/floooh/cimgui-sokol-starterkit/blob/f6bb62ddcdb1b2ea0cdd453800861adbe1798330/sokol/sokol.c#L4

...with:

```c
#define SOKOL_GLES3
```

...and then add `EGL` to the Linux link libraries here:

https://github.com/floooh/cimgui-sokol-starterkit/blob/f6bb62ddcdb1b2ea0cdd453800861adbe1798330/CMakeLists.txt#L41

...and try building again.

**Comment by yatsam** [comment]
Thanks for your prompt reply! It works!!
There was also an occurrence of sokol_GLCORE to be changed to sokol_GLES3 on line 13 of sokol.c

Cheers!
