### ISSUE TITLE
Adding shader build to CMake setup?

### ISSUE THREAD

**Issue by fiserj** [floooh/cimgui-sokol-starterkit#3]
First of all, let me say I love Sokol libs and the ease of their setup and minimum footprint!

I have similar starter kit for my personal projects using Sokol and I also wrapped the shader compiler from sokol-tools-bin with a CMake script, so that I could have the shaders be built as part of the CMake build machinery.

If you're interested, I could make a PR - or do you think it would unnecessarily complicate the demo?

**Comment by floooh** [comment]
I don't want to add any additional complexity to this particular starter kit (because for ImGui the required shaders are already embedded in sokol_imgui.h). Might be a good idea for a separate starter kit which would focus on 3D rendering.
