### ISSUE TITLE
WASM build on Windows ?

### ISSUE THREAD

**Issue by jbsiraudin** [floooh/cimgui-sokol-starterkit#8]
Hi there,
Probably a stupid question coming, I'm new to all this, so sorry in advance.

I unsuccessfully tried building with emscripten on Windows 10 (without using WSL), and I'm having trouble understanding this line in the README.md:
> (this procedure should also work on Windows with ```make``` in the path, but is currently untested)

What do you mean by `make in the path`?

Many thanks!

**Comment by floooh** [comment]
Sorry for being unclear :) It means that the ```make``` tool (https://www.gnu.org/software/make/manual/make.html) must be installed and in the terminal's search path.

The easiest way is IMHO ```scoop install make```, assuming that scoop has been installed (https://scoop.sh/)

Cheers!
